console.log(document.body.children)
let tabel1 = document.createElement("table");
let thead1 = document.createElement("thead");
let tbody1 = document.createElement("tbody");
let trow1 = document.createElement("tr");
let th1 = document.createElement("th");
let th2 = document.createElement("th");
let trow2 = document.createElement("tr");
let trow3 = document.createElement("tr");
let td1 = document.createElement("td");
let td2 = document.createElement("td");
let td3 = document.createElement("td");
let td4 = document.createElement("td");
th1.innerHTML = "header1";
th2.innerHTML = "header2";
td1.innerHTML = "data1";
td2.innerHTML = "data2";
td3.innerHTML = "data3";
td4.innerHTML = "data4";
trow1.style.color = "red"
tabel1.appendChild(thead1);
tabel1.appendChild(tbody1);
thead1.appendChild(trow1);
trow1.appendChild(th1);
trow1.appendChild(th2);
tbody1.appendChild(trow2);
tbody1.appendChild(trow3);
trow2.appendChild(td1);
trow2.appendChild(td2);
trow3.appendChild(td3);
trow3.appendChild(td4);
document.body.appendChild(tabel1);
